### ISSUE TITLE
Unable to verify trade documents on Stability and Hedera on Custom Verifier

### ISSUE THREAD

**Issue by manishraana** [TradeTrust/tradetrust-core#19]
Hi Team,

We developed a custom document verifier using **tt-verify** around six months ago, which was functioning well with **Ethereum**, **Polygon**, and **XDC** networks. Recently, we added support for creating documents on **Stability** and **Hedera** chains. However, we're experiencing issues verifying these documents specifically on **Stability** and **Hedera** chains through our custom verifier.

**Actions We have Taken:**
We upgraded the dependencies to their latest versions but encountered the same issue.
Verification for other chains (**Ethereum**, **Polygon**, **XDC**) continues to work as expected.

Could you please provide guidance or recommendations on resolving this issue? Are there any additional dependencies, configurations, or specific checks required to ensure successful document verification on **Stability** and **Hedera** chains?

Also on upgrading our existing files are not getting verified, Is there any additional configurations we need to add ?

![Screenshot 2024-11-11 at 11 40 20 AM](https://github.com/user-attachments/assets/476de4d5-8d9a-4741-a117-990c39b2d5ed)

**Comment by pohhendry** [comment]
Hey Manish, Hedera is not 100% supported at the moment.

If we can concentrate on Stability, perhaps you can double check your DNS text record has this issuer's (ending with 0bFB) record in place?

I assume you are using the DNS-TXT method, and for more information you can check this guide:
https://docs.tradetrust.io/docs/topics/introduction/issuer-method-dns-txt

**Comment by manish-raana** [comment]
@pohhendry 
Yes we are using DNS-TXT method,
We tried verifying same files on https://ref.tradetrust.io/ for stability and hedera, and both files are getting verified successfully, but on our verifier it is causing the identity issue. We tried the same files.

**Comment by nghaninn** [comment]
Hi @manish-raana 

I'm wondering if you could provide any code snippets or a sample of the document that you are trying to verify. It's hard for us to deduce the error that you are facing.

I have tested with some sample code against Sepolia and Stability Testnet, and they are working fine.
For your reference, https://github.com/nghaninn/tradetrust-sample-test/blob/main/src/index.js
Result of the verification: https://github.com/nghaninn/tradetrust-sample-test/blob/main/README.md

Apart from the sample, a few things to clarify. If you could share with us:
- current node version 
- version of the @tradetrust-tt/tt-verify
that you are running for your project.

**Comment by manishraana** [comment]
Hi @nghaninn 

Thank you for responding to our query,

We are currently using the following versions
 **@tradetrust-tt/tt-verify** : **8.4.0** we tried upgrading to latest version as well
**node** : **18.20.4** but we tried upgrading to 22 as well

Here is our sample tt file generated on stability mainnet [https://github.com/PDC-Finance/doc-sample/blob/main/bill-of-lading-stability.tt](https://github.com/PDC-Finance/doc-sample/blob/main/bill-of-lading-stability.tt)


We are using it like this from verificationBuilder
![Screenshot 2024-11-13 at 12 10 08 PM](https://github.com/user-attachments/assets/781cd4fb-7077-442b-b941-734224ffc824)

**Note: It is getting verified properly on [https://ref.tradetrust.io/viewer](https://ref.tradetrust.io/viewer)**

**Comment by nghaninn** [comment]
@manish-raana Please uninstall and install **@tradetrust-tt/tt-verify** again. 
The latest version of **@tradetrust-tt/tt-verify** is currenlt v8.10.2.

My guess is that you probably running a higher node version > node 18 previously.

**Comment by manishraana** [comment]
@nghaninn 

I tried upgrading it to the latest version to **8.10.2** but now it's returning a different error.
Here is it.

![Screenshot 2024-11-13 at 2 23 18 PM](https://github.com/user-attachments/assets/463e4c77-b134-4d67-91b1-313764df995f)


![Screenshot 2024-11-13 at 2 22 25 PM](https://github.com/user-attachments/assets/56dc36e0-3653-4f1f-8994-27af82c2ca99)

**Node we are using 18.20.4**

![Screenshot 2024-11-13 at 2 23 40 PM](https://github.com/user-attachments/assets/93a471d9-b357-4ddc-892f-bcd265e2a788)

**Comment by nghaninn** [comment]
@manish-raana
I see. There seems to be additional string quotation in your DNS value.

https://dns.google/query?name=mebl-stability-local.blockpeer.finance&rr_type=TXT&ecs=
<img width="1009" alt="Screenshot 2024-11-14 at 08 24 03" src="https://github.com/user-attachments/assets/0af53e8e-48a5-4e27-91a8-ab052392fce1">

Here's a reference of the DNS record.
https://dns.google/query?name=example.tradetrust.io&rr_type=TXT&ecs=

**Comment by manishraana** [comment]
Yes, but the same way it is working fine on other chains, let us try removing the additional parts in the string.

**Comment by nghaninn** [comment]
@manish-raana, would you be willing to share the DNS names of the other chains you've used, to help us with our investigation?

**Comment by manishraana** [comment]
Hi @nghaninn,

Here is the another one on XDC Mainnet

[https://dns.google/query?name=MKEINVOICE-STAGING.BLOCKPEER.FINANCE&rr_type=TXT&ecs=](https://dns.google/query?name=MKEINVOICE-STAGING.BLOCKPEER.FINANCE&rr_type=TXT&ecs=)

**Comment by nghaninn** [comment]
Hi @manish-raana,

After extensive testing, I noticed that the error was not related to the DNS records. However, it is due to a missing detail in the document that you generated. It is recommended that you include the network field in the generated document.

Example: 
- V2 Document: https://github.com/nghaninn/tradetrust-sample-test/blob/b263289447cb4f494b284bbbf6ac38f0914cdbaa/src/index.js#L163
- V3 Document: https://github.com/nghaninn/tradetrust-sample-test/blob/b263289447cb4f494b284bbbf6ac38f0914cdbaa/src/index.js#L253

Without the network field, the verifier will likely fall back to the default provider within your code implementation. 
_Without any reference to your implementation, this is my best deduction._

_____

With reference to the `openAttestationDnsTxt` [code](https://github.com/TradeTrust/tt-verify/blob/32b1c580903ac1a3278a5d9d841bff418c0628e8/src/verifiers/issuerIdentity/dnsTxt/openAttestationDnsTxt.ts#L30).
```
  const network = await options.provider.getNetwork();
  const records = await getDocumentStoreRecords(location);
  const matchingRecord = records.find(
    (record) =>
      record.addr.toLowerCase() === smartContractAddress.toLowerCase() &&
      record.netId === network.chainId.toString(10) &&
      record.type === "openatts" &&
      (record.net === "ethereum" || record.net === "hedera")
```
This code extracts the network ID from the provided provider.

For testing, I have added your document into the [sample code](https://github.com/nghaninn/tradetrust-sample-test/blob/b263289447cb4f494b284bbbf6ac38f0914cdbaa/src/index.js#L186).
Since your document did not provide any network value, the sample code defaults to Sepolia (11155111) as the provider, resulting in the error ` "Matching DNS record not found for 0x7090985Ad3965b0181eEa03ba872471755880bFB"`.

<details>
<summary>Error Log results</summary>

```
===Verifying wrapped V2 Stability document===
chainId: 11155111
[
  {
    "type": "DOCUMENT_INTEGRITY",
    "name": "OpenAttestationHash",
    "data": true,
    "status": "VALID"
  },
  {
    "name": "OpenAttestationEthereumTokenRegistryStatus",
    "type": "DOCUMENT_STATUS",
    "reason": {
      "message": "Token registry is not found",
      "code": 1,
      "codeString": "DOCUMENT_NOT_MINTED"
    },
    "status": "INVALID",
    "data": {
      "mintedOnAll": false,
      "details": [
        {
          "minted": false,
          "address": "0x7090985Ad3965b0181eEa03ba872471755880bFB",
          "reason": {
            "message": "Token registry is not found",
            "code": 1,
            "codeString": "DOCUMENT_NOT_MINTED"
          }
        }
      ]
    }
  },
  {
    "status": "SKIPPED",
    "type": "DOCUMENT_STATUS",
    "name": "OpenAttestationEthereumDocumentStoreStatus",
    "reason": {
      "code": 4,
      "codeString": "SKIPPED",
      "message": "Document issuers doesn't have \"documentStore\" or \"certificateStore\" property or DOCUMENT_STORE method"
    }
  },
  {
    "status": "SKIPPED",
    "type": "DOCUMENT_STATUS",
    "name": "OpenAttestationDidSignedDocumentStatus",
    "reason": {
      "code": 0,
      "codeString": "SKIPPED",
      "message": "Document was not signed by DID directly"
    }
  },
  {
    "name": "OpenAttestationDnsTxtIdentityProof",
    "type": "ISSUER_IDENTITY",
    "data": [
      {
        "status": "INVALID",
        "location": "mebl-stability-local.blockpeer.finance",
        "value": "0x7090985Ad3965b0181eEa03ba872471755880bFB",
        "reason": {
          "message": "Matching DNS record not found for 0x7090985Ad3965b0181eEa03ba872471755880bFB",
          "code": 4,
          "codeString": "MATCHING_RECORD_NOT_FOUND"
        }
      }
    ],
    "reason": {
      "message": "Matching DNS record not found for 0x7090985Ad3965b0181eEa03ba872471755880bFB",
      "code": 4,
      "codeString": "MATCHING_RECORD_NOT_FOUND"
    },
    "status": "INVALID"
  },
  {
    "status": "SKIPPED",
    "type": "ISSUER_IDENTITY",
    "name": "OpenAttestationDnsDidIdentityProof",
    "reason": {
      "code": 0,
      "codeString": "SKIPPED",
      "message": "Document was not issued using DNS-DID"
    }
  }
]
isValid false
```
</details>

_____

With a minor tweak of the default `chainId` value to [101010](https://github.com/nghaninn/tradetrust-sample-test/blob/b263289447cb4f494b284bbbf6ac38f0914cdbaa/src/index.js#L23) in the sample code implementation, we successfully achieved a positive result.

<details>
<summary>Success Log Result</summary>

```
===Verifying wrapped V2 Stability document===
chainId: 101010
[
  {
    "type": "DOCUMENT_INTEGRITY",
    "name": "OpenAttestationHash",
    "data": true,
    "status": "VALID"
  },
  {
    "name": "OpenAttestationEthereumTokenRegistryStatus",
    "type": "DOCUMENT_STATUS",
    "status": "VALID",
    "data": {
      "mintedOnAll": true,
      "details": [
        {
          "minted": true,
          "address": "0x7090985Ad3965b0181eEa03ba872471755880bFB"
        }
      ]
    }
  },
  {
    "status": "SKIPPED",
    "type": "DOCUMENT_STATUS",
    "name": "OpenAttestationEthereumDocumentStoreStatus",
    "reason": {
      "code": 4,
      "codeString": "SKIPPED",
      "message": "Document issuers doesn't have \"documentStore\" or \"certificateStore\" property or DOCUMENT_STORE method"
    }
  },
  {
    "status": "SKIPPED",
    "type": "DOCUMENT_STATUS",
    "name": "OpenAttestationDidSignedDocumentStatus",
    "reason": {
      "code": 0,
      "codeString": "SKIPPED",
      "message": "Document was not signed by DID directly"
    }
  },
  {
    "name": "OpenAttestationDnsTxtIdentityProof",
    "type": "ISSUER_IDENTITY",
    "data": [
      {
        "status": "VALID",
        "location": "mebl-stability-local.blockpeer.finance",
        "value": "0x7090985Ad3965b0181eEa03ba872471755880bFB"
      }
    ],
    "status": "VALID"
  },
  {
    "status": "SKIPPED",
    "type": "ISSUER_IDENTITY",
    "name": "OpenAttestationDnsDidIdentityProof",
    "reason": {
      "code": 0,
      "codeString": "SKIPPED",
      "message": "Document was not issued using DNS-DID"
    }
  }
]
isValid true
```
</details>

_____

Additional testing was conducted using your sample document on ref.tradetrust.io. [Recording](https://www.loom.com/share/eb3dafa72aac486b9606541cb0cb9103?sid=04554fa9-5d69-4e39-9cff-f6e6f2573e85)
The test resulted in success only when we manually switched the network to 'Stability'.

However, for a document that includes a network value, the network switching is triggered automatically, and the document is displayed correctly. [Recording](https://www.loom.com/share/753dc3a8337642c2890b3a2e86165628?sid=6095d719-0850-4a15-be71-de71d633a531)

_____

Please don't hesitate to reach out if you're still encountering any issues. We're here to help and want to ensure everything is working smoothly for you!

**Comment by manishraana** [comment]
@nghaninn 

Thank you for looking into this issue and debugging it on priority, 

I will definitely try the solution you have shared and get back to you with the responses.

**Comment by nghaninn** [comment]
Hi @manish-raana

I hope everything is well. Since there's no response, I will proceed to close this issue. If you have any concerns or further issues, please feel free to reopen. Thanks!

**Comment by manishraana** [comment]
Hi @nghaninn 

I have created a new document which have the network chain and chainId, I have tried your [sample code](https://github.com/nghaninn/tradetrust-sample-test/blob/b263289447cb4f494b284bbbf6ac38f0914cdbaa/src/index.js#L186) to verify it on stability, it is verifying on the sample app that you have shared.

I created a [Sample React App](https://github.com/manishraana/sample-react-verifier) using the same modules just to test it on the frontend side, used the same functions and same approach there also, but on react side it is retuning not valid.

Here is a [recorded video](https://www.loom.com/share/164eb887550e40c5b141ffddc1f4aa76?sid=836bc379-8d48-45a5-89fa-f236b4c697da) for the same.

Can you please check the sample react code, Is there anything I'm missing on it.

**Comment by nghaninn** [comment]
Hi @manish-raana

The issue you are facing is due to a configuration-related issue.

I went through your repo and found a resolution, and I have made a PR to your sample repo:
https://github.com/manishraana/sample-react-verifier/pull/1

**Comment by manishraana** [comment]
Hi @nghaninn, 

Thank you for your excellent support in resolving the issue. The solution provided in the PR works perfectly. 

I really appreciate your prompt assistance and the time you took to help fix this problem.

Hence closing the issue.

**Comment by nghaninn** [comment]
Hi @manish-raana 

Good to hear that!

Also forgot to mention that, the chain value needs to be `FREE` for 101010.
https://github.com/manishraana/sample-react-verifier/blob/761a69174a24e72df0569bc4d1c9e9574ac20bea/src/App.tsx#L62

I needs to satisfies the currency value as shown here.
https://github.com/TradeTrust/tradetrust-core/blob/127d7e5e93144019491ab234ee67fc9dd35c4fd0/src/utils/constants/supportedChains.ts#L193

The sample document in your [Sample React App](https://github.com/manishraana/sample-react-verifier) does not verify in https://ref.tradetrust.io/

Do many sure you have a systematic way to generate the .tt document, and actively verify it as against TradeTrust verifiers. 
- https://ref.tradetrust.io/
- https://dev.tradetrust.io/

**Comment by manishraana** [comment]
Hi @nghaninn 

Thank you for providing useful insights.
We will definitely use your suggestions and make the required changes in our code as well.
